[profile.default]
solc_version = "0.8.24"
auto_detect_solc = false
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
  { access = "read", path = "./src" },
  { access = "read", path = "./lib" },
  { access = "read-write", path = "./out" }
]

[fmt]
line_length = 100
tab_width = 4

[profile.deploy]
via_ir = true
